[package]
name = "aim"
version = "0.0.7"
edition = "2021"
description = "A command line download/upload tool with resume."
categories = ["command-line-utilities"]
keywords = ["download", "upload", "resume"]
repository = "https://github.com/mihaigalos/aim"
documentation = "https://github.com/mihaigalos/aim/blob/master/README.md"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_ftp = "6.0.0"
async-stream = "0.3.2"
clap = "2.33.2"
dotenv = "0.15.0"
failure = "0.1.8"
futures-util = "0.3.14"
indicatif = "0.16.2"
netrc = "0.4.1"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11.3", features = ["stream"] }
sha2 = "0.10.0"
strfmt = "0.1.6"
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = {version="0.6.9", features = ["full"]}
url = "1.7.2"
