[package]
name = "ship"
version = "0.0.1"
edition = "2021"
description = "github.com/mihaigalos/ship"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_ftp = "6.0.0"
async-stream = "0.3.2"
clap = "2.33.2"
dotenv = "0.15.0"
failure = "0.1.8"
futures-util = "0.3.14"
indicatif = "0.16.2"
reqwest = { version = "0.11.3", features = ["stream"] }
sha256 = "1.0.2"
strfmt = "0.1.6"
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = {version="0.6.9", features = ["full"]}
url = "1.7.2"
