[package]
name = "aim"
version = "1.1.0"
edition = "2021"
description = "🎯 A command line download/upload tool with resume."
categories = [
    "HTTP client",
    "command-line-utilities",
    "network-programming",
    "web-programming::http-client"
]
keywords = [ 
    "cli",
    "download",
    "resume",
    "upload"
]
repository = "https://github.com/mihaigalos/aim"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_ftp = "6.0.0"
async-stream = "0.3.2"
clap = "2.33.2"
custom_error = "1.9.2"
dotenv = "0.15.0"
futures-util = "0.3.14"
indicatif = "0.16.2"
netrc = "0.4.1"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11.3", features = ["stream"] }
sha2 = "0.10.0"
ssh2 = "0.9.3"
strfmt = "0.1.6"
tokio = { version = "1.14.0", features = ["full"] }
tokio-util = {version="0.6.9", features = ["full"]}
url = "1.7.2"
warpy = "0.1.2"

regex = "1.5.4" # Remove this dep once this is merged: https://github.com/sathishsoundharajan/untildify/pull/2
#untildify = "0.1.0" Remove comment once this is merged: https://github.com/sathishsoundharajan/untildify/pull/2

[dev-dependencies]
serial_test = "0.5.1"
