name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/audit.toml'

jobs:
  audit:
    uses: mihaigalos/config/.github/workflows/rust-audit.yaml@main
